[build]
  publish = "apps/admin-dashboard/dist"
  command = "npx --yes pnpm@latest install && pnpm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--force"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 