[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile.simple"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 